export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';

export const API_STATUS_STARTED = 'API_STATUS_STARTED'; 
export const API_STATUS_FAILURE = 'API_STATUS_FAILURE';